name: Generate requirements.txt

on:
  push:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pyproject.toml' ]
  workflow_dispatch:

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Generate requirements.txt
        run: uv pip compile pyproject.toml -o requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🤖 Auto-update requirements.txt from pyproject.toml
          branch: main